---
title: "Garmin data from Chocoholic Frolic in St. Paul"
format: html
editor: visual
---

```{r, message=F, warning=FALSE}
library("tidyverse")
library("ggmap")
library("FITfileR")
library("leaflet")
```

```{r}
fr945_data <- readFitFile(fileName = "~/Downloads/9922263791_ACTIVITY.fit")
```

```{r}

fr945_data_allrecords <- records(fr945_data) %>% 
  bind_rows() %>% 
  arrange(timestamp) 

glimpse(fr945_data_allrecords)
```

```{r}
coords <- fr945_data_allrecords |>
  select(position_long, position_lat)
```

A map of the points my watch picked up

```{r}
m <- coords |>
  as.matrix() |>
  leaflet() |>
  addTiles() |>
  addPolylines()

m
```

# Heart rate data
First a plot of heart rate based on distance into the 10k

```{r}
fr945_data_allrecords |>
  ggplot() +
    geom_line(aes(x = distance, y = heart_rate), color = "red") +
    labs(y = "Heart Rate", x = "Meters into 10 K")
```

Scatter plot of elevation
```{r}
fr945_data_allrecords |>
  ggplot(aes(x = distance, y = enhanced_altitude)) +
    geom_point() 
```
```{r}
fr945_data_allrecords |>
  ggplot(aes(x = distance, y = enhanced_speed*2.237)) +
    geom_point() +
    labs(y = "Speed in MPH", x = "Meters into 10K")
```
